Remote_theme: pages-themes/midnight@v0.2.0
title: "TAKES_DB"
lang: ja

# 👇 これを追記：すべてのマークダウンファイルに自動で default レイアウトを適用する
defaults:
  - scope:
      path: "" # リポジトリ内のすべてのファイルを対象にする
    values:
      layout: "default"
